### ISSUE TITLE
Management of quota

### ISSUE THREAD

**Issue by tyskjohan** [oravirt/ansible-oracle-modules#114]
I am thinking to add possibility to manage quotas on tablespaces. I am looking for input on whether I should do this in oracle_user, oracle_tablespace or create a new oracle_quota module.

My current thinking is to add it to oracle_user such as:

```yaml
oracle_user:
  hostname: localhost
  service_name: orcl
  user: system
  password: manager
  schema: myschema
  schema_password: mypass
  default_tablespace: test
  state: present
  grants: dba
  quota:
  - tablespace1:unlimited
  - tablespace2:10M
```

The main disadvantage is that quota revocation can't be easily handled here, but that is not something I need. I could imagine a `quota_mode` but I'll leave that to someone else :-)
