### ISSUE TITLE
How to spool the sql script ?

### ISSUE THREAD

**Issue by anandsolomon** [oravirt/ansible-oracle-modules#121]
Hi,
I need to run a playbook with spool like below. I am not able to use oracle_sql module to exeute.

spool log.log
select username from dba_users;
spool off;

I get the below error
    },
    "msg": "Something went wrong while executing sql - ORA-00900: invalid SQL statement sql: spool log.log\nselect username from dba_users"
}

**Comment by oravirt** [comment]
Hi,
Yes, that is not supported right now. I might add that as a feature eventually, but in the meantime you should be able to register the module output and use that in a template.

**Comment by anandsolomon** [comment]
Thanks very much. This is what I am trying to do. Is there a way we can do ?

1 Task.
spool script.sql
select username from dba_users;
spool off;

2 task 
@script.sql

**Comment by oravirt** [comment]
This is the overall (simplistic) way of achieving what you want, you may have to parse the output in the template somehow but I'll leave that as an exercise ;-)
 
pseudo-code:

```
- name: run sql
  oracle_sql:
      sql: "select ......."
    register: sqloutput

- name: build sqlfile from template
  template:
      src: mysqltemplate.sql.j2
      dest: /where/ever/script.sql

- name: run sqlscript
  oracle_sql:
     script: /where/ever/script.sql
```

And then the minimum content of the template is something like:


`cat mysqltemplate.sql.j2`

```
-- This is the sql template which will take the output 
-- from the first oracle_sql task and paste it into the template
{{ sqlputput.stdout_lines }}
```
