### ISSUE TITLE
Not able to set the oracle environment and run crsctl command

### ISSUE THREAD

**Issue by akshaynbora** [oravirt/ansible-oracle-modules#144]
Hi , 

I am not able to  set the oracle environment and hence cant run crsctl commands. I wrote below code. Someone please suggest me.

---

- hosts: all
  vars_prompt:
  - name: SID
    prompt: "Enter the Oracle SID"
    private: no
  - name: HOME
    prompt: "Enter the Oracle HOME"
    private: no
  tasks:
   - name: Setup the environemtnal variable
     shell:
      export ORACLE_SID={{ SID }}
      export ORACLE_HOME={{ HOME }}
      export PATH=$PATH:$ORACLE_HOME/bin
      crsctl stat res -t
[oracle@rac2 ~]$

**Comment by oravirt** [comment]
Hi,
Do you have a problem with one of the modules in this repo or is this just a general Ansible question? If it is the latter this (https://groups.google.com/forum/#!forum/ansible-project) is probably a better place to ask.

Anyway, if you want to inject environment variables into your play, you should use the `environment` keyword  in your playbook 
e.g
(https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html)

```
- name: run crsctl
  shell: $ORACLE_HOME/bin/crsctl stat res -t
  environment:
          ORACLE_SID: "xxx"
          ORACLE_HOME: "yyy"
```
