### ISSUE TITLE
oracle_user: ORA-01031: insufficient privileges when running as system

### ISSUE THREAD

**Issue by ilmarkerm** [oravirt/ansible-oracle-modules#2]
12.1.0.2 non-cdb

Ansible code:
```
- name: Create oracle schema
  local_action:
    module: oracle_user
    hostname: "{{ ansible_fqdn }}"
    service_name: "{{ oracle_sid }}"
    user: system
    password: "{{ oracle_syspassword }}"
    schema: "{{ ec2_tag_oracleschema }}"
    schema_password: "{{ ec2_tag_oracleschema }}"
    grants:
      - create session
      - resource
      - unlimited tablespace
  become: no
  when: ec2_tag_oracleschema is defined
  environment:
    ORACLE_HOME: /usr/lib/oracle/12.1/client64
    LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
```

Running first time creates the user just fine, but when re-running:

fatal: [10.250.0.140 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "ORA-01031: insufficient privileges\n: sql: select password from sys.user$ where name = upper('test123')"}
