### ISSUE TITLE
Oracle Client library cannot be loaded error while using oracle_sql module

### ISSUE THREAD

**Issue by rajameka86** [oravirt/ansible-oracle-modules#45]
Hello,
Thank you for the modules, You guys are simply Awesome!!!

I am getting below error message when I try to use the oracle_sql module. 

My set up Ansible Master running on Linux host which has separate set of users based up on environment and those are connecting to remote DB servers and executing the .SQL files or sql statements by using shell on remote server. I would liek to avoid this shell and use this module instead but I am getting below error. Looks like this module didn't source the environment variables.   I tried multiple scenarios didn't find much help.  

    "msg": "Could not connect to database - DPI-1047: 64-bit Oracle Client library cannot be loaded: \"libclntsh.so: cannot open shared object file: No such file or directory\". See https://oracle.github.io/odpi/doc/installation.html#linux for help, connect descriptor: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = X.X.X.X)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = orcl))))))"

Please let me know if you ever face this kind of issue or please guide me through on how to handle remote server execution with remote users other than user "Oracle"

Thanks and Regards
Raj

**Comment by oravirt** [comment]
Thank you!

I'd need to see the playbook to be able to debug properly, but I guess ORACLE_HOME & LD_LIBRARY_PATH doesn't get injected properly.

The easiest way to do it is to use the 'environment:'  directive

```
- name: run sql
   oracle_sql: ....
   environment:
        ORACLE_HOME: /path/to/oracle_home
        LD_LIBRARY_PATH: /path/to/oracle_home/lib

```   
or better yet, make the environment thing a variable that you just reference

Let me know if this works or if I you need more assistance

regards
/M

**Comment by rajameka86** [comment]
Thanks for reply. Just one thing to clarify do I need to have Oracle express edition needs to be installed on Ansible Master to talk to remote DB's? as you mentioned above I dont have ORACLE_HOME, however LD_LIBRARY_PATH was in place as I installed oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm. Please correct me if I misinterpreted your answer. Thanks  a ton.

**Comment by rajameka86** [comment]
Thanks for reply, OK I did added the environment values as below and ran the play.  
- name: run sql
  oracle_sql:
        username: "{{ admin }}"
        password: "{{ admin_password }}"
  environment:
        ORACLE_HOME: /u01/app/oracle/product/11.2.0.4/db_1
        LD_LIBRARY_PATH: /u01/app/oracle/product/11.2.0.4/db_1/lib
  service_name: (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = sandbox_IP)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = orcl)))
  sql: 'select * from all_users;'

My requirement is login to the remote databases which are encrypted and I need to get the list out of the database and decrypt the schema name and update the hot fixes which are on particular version from ansible master.  There is no local account on to DB boxes everything should be done remotely from ansible master :) tricky scenario but we are doing it :100:

**Comment by oravirt** [comment]
Hi, sorry about the late reply.

So, I think you'd have to do this:

```
- name: run sql
  oracle_sql:
  username: "{{ admin }}"
  password: "{{ admin_password }}"
  hostname: sandbox_IP
  service_name:  orcl
  sql: 'select * from all_users'
  environment:
          ORACLE_HOME: /u01/app/oracle/product/11.2.0.4/db_1
          LD_LIBRARY_PATH: /u01/app/oracle/product/11.2.0.4/db_1/lib
  
```
cx_Oracle will construct the connection string based on the hostname, service_name and port. So you don't have to pass in the entire string yourself.

Hope this helps.

regards
/M
