### ISSUE TITLE
DPI-1047 on CentOS 7.4.1708, Python 2.7.5, cx_Oracle 6.2.1, and oracle-instantclient12.2

### ISSUE THREAD

**Issue by blucas-accela** [oravirt/ansible-oracle-modules#46]
I'm running into this issue when trying out a playbook. I saw a similar issue and tried adding the environment variables as shown in the playbook but to no avail.

Command:
ansible-playbook -i hosts oracle.yml -e "user=**** password=*** service_name=***"

oracle.yml contents

    - hosts: oracle
  tasks:
    - name: "Run SQL" 
      oracle_sql:
        username: "{{user}}"
        password: "{{password}}"
        service_name: "{{service_name}}"
        hostname: "***"
        port: "1521"
        sql: 'select username from dba_users'
      environment:
        ORACLE_HOME: /usr/lib/oracle/12.2/client64
        LD_LIBRARY_PATH: /usr/lib/oracle/12.2/client64/lib

ERROR:
    fatal: []: FAILED! => {"changed": false, "msg": "Could not connect to database - DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help, connect descriptor: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=***)))"}

**Comment by oravirt** [comment]
Hi,
What does the 'hosts' file look like?

**Comment by blucas-accela** [comment]
It's pretty simple:
[oracle]
10.1.2.3

**Comment by oravirt** [comment]
Ok - I'm just trying to understand your setup.

So, the client is installed under  /usr/lib/oracle/12.2/client64 on the host 10.1.2.3? 
And cx_Oracle is also installed on the same host?

**Comment by blucas-accela** [comment]
No problem! I gave up on the instant client and installed the full Oracle 12.2.0.1 db client at /opt/oracle/product/12.2.0/client_1 on the remote linux host (not the Oracle host 10.1.2.3 which has its own full db server installation).

cx_Oracle is installed on both hosts.

**Comment by oravirt** [comment]
ok, cool.

Regardless of the host you're connecting to, ORACLE_HOME & LD_LIBRARY_PATH has to match paths on 'that' host. 
In the example you provided, the module is expecting the paths to exist on the 10.1.2.3 host.

So if you're connecting to the 'remote linux host' then ORACLE_HOME should be /opt/oracle/product/12.2.0/client_1 
and if you're connecting to the the 10.1.2.3 host ORACLE_HOME should be the path to 'its own full db server installation'

**Comment by blucas-accela** [comment]
ansible server = 10.111.0.200 running cx_Oracle with Oracle 12.2 client at  /opt/oracle/product/12.2.0/client_1
db host = 10.1.2.3 running Oracle 11.2.0.3 enterprise edition at /app/oracle/product/11.2.0/db

If I understand your last comment correctly, then the ansible server host at 10.111.0.200 needs to set environment variables like this because it is connecting to the remote db host:
LD_LIBRARY_PATH=/app/oracle/product/11.2.0/db/lib
ORACLE_HOME=/app/oracle/product/11.2.0/db

Is that correct? If so, I just tried that and ran into the same error. 

[root@onscpt library]# env | grep oracle
LD_LIBRARY_PATH=/app/oracle/product/11.2.0/db/lib
ORACLE_HOME=/app/oracle/product/11.2.0/db
[root@onscpt library]# cd ..
[root@onscpt projects]# ansible-playbook -i hosts oracle.yml

PLAY [oracle] ****************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************
ok: [10.1.2.3]

TASK [Run SQL] ***************************************************************************************************************************************************************
fatal: [10.1.2.3]: FAILED! => {"changed": false, "msg": "Could not connect to database - DPI-1047: 64-bit Oracle Client library cannot be loaded: \"libclntsh.so: cannot open shared object file: No such file or directory\". See https://oracle.github.io/odpi/doc/installation.html#linux for help, connect descriptor: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.2.3)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=***)))"}
	to retry, use: --limit @/home/accelaops/projects/oracle.retry

PLAY RECAP *******************************************************************************************************************************************************************
10.1.2.3                 : ok=1    changed=0    unreachable=0    failed=1

**Comment by oravirt** [comment]
Just so I have the config correct:
- You're executing the playbook (as in running ansible-playbook) on the host 10.111.0.200
- The playbook is connecting to 10.1.2.3 and trying to run the oracle_sql module on that host.

If the above is correct, then ORACLE_HOME & LD_LIBRARY_PATH has to match the paths on 10.1.2.3 (which seems to be what you just described)

What you could do to make sure cx_Oracle is working as intended: 
1. log on to the db host
2. set ORACLE_HOME & LD_LIBRARY_PATH
3. Run python and try to import cx_Oracle
```
$ python
Python 2.7.14 (default, Dec 11 2017, 16:08:01) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> 
```

And just to clarify, for the playbook to work you have to set the variables in the playbook, not at the OS level. They will be injected into the play by Ansible.

**Comment by blucas-accela** [comment]
OK, I updated the ones in the playbook to use the db host locations and made some progress. I just ran a simple SELECT statement. Is it designed to output the results of that SELECT or just execute the statement alone? My statement was just 'select username from dba_users'

[root@onscpt projects]# ansible-playbook -i hosts oracle.yml

PLAY [oracle] ****************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************
ok: [10.1.2.3]

TASK [Run SQL] ***************************************************************************************************************************************************************
ok: [10.1.2.3]

PLAY RECAP *******************************************************************************************************************************************************************
10.1.2.3                 : ok=2    changed=0    unreachable=0    failed=0

**Comment by oravirt** [comment]
Great!

This is standard Ansible behaviour, no output is shown by default. If you want the output from any module you have to add `-v` when you run the playbook.
If you want to somehow use the output you can use the `register` directive to store the output, and later act on it.

This module will output the resultset of the query if it's a select statement, so I guess you should see all usernames.

**Comment by Ricuxo** [comment]
Could you please help me?
I have the same error, and I do not know how to correct it.
Running from a remote machine, or from the database server itself encounters the same error.
Here is my test environment:

Database server:
Oracle Linux Server release 7.6
Python 2.7.5

```
[oracle @ alderaan ansible] $ cat hosts
[oracle]
192.168.1.150
```

```
[oracle @ alderaan library] $ ls -ltr
total 32
drwxr-xr-x. 3 oracle oinstall 4096 Apr 23 20:32 ansible-oracle-modules
-rwxr-xr-x. 1 oracle oinstall 16649 Apr 23 20:32 oracle_user
-rwxr-xr-x. 1 oracle oinstall 7794 May 3 18:27 oracle_sql
```

```
[oracle @ alderaan ansible] $ cat oracle.yaml
---
- hosts: oracle
  user: oracle

  vars:
      oracle_home: /u01/app/oracle/product/12.2.0.1/db_1
      hostname: "192.168.1.150"
      service_name: ORCL
      set_init_mode: sysdba
      set_init_user: sys
      user: system
      password: oracle
      oracle_env:
             ORACLE_HOME: "{{oracle_home}}"
             LD_LIBRARY_PATH: "{{oracle_home}} / lib"

  tasks
    - name: Run SQL
      oracle_sql:
        username: "{{user}}"
        password: "{{password}}"
        service_name: "{{service_name}}"
        sql: "select username from dba_users"
```

```
[oracle@alderaan ansible]$ python
Python 2.7.5 (default, Apr  9 2019, 16:02:27) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> exit()
```


```
[oracle @ alderaan ansible] $ echo $ ORACLE_HOME; echo $ LD_LIBRARY_PATH
/u01/app/oracle/product/12.2.0.1/db_1
/u01/app/oracle/product/12.2.0.1/db_1/lib:/lib:/usr/lib
```

```
[oracle @ alderaan ansible] $ locate libclntsh.so
/u01/app/12.2.0.1/grid/inventory/Scripts/ext/lib/libclntsh.so.12.1
/u01/app/12.2.0.1/grid/inventory/backup/2019-04-20_06-47-09PM/Scripts/ext/lib/libclntsh.so.12.1
/u01/app/12.2.0.1/grid/inventory/backup/2019-04-20_06-47-09PM/Scripts/ext/lib/libclntsh.so.12.1.ouibak
/u01/app/12.2.0.1/grid/inventory/backup/2019-04-20_06-47-09PM/Scripts/ext/lib/libclntsh.so.12.1.ouibak.1
/u01/app/12.2.0.1/grid/lib/libclntsh.so
/u01/app/12.2.0.1/grid/lib/libclntsh.so.10.1
/u01/app/12.2.0.1/grid/lib/libclntsh.so.11.1
/u01/app/12.2.0.1/grid/lib/libclntsh.so.12.1
/u01/app/oracle/product/12.2.0.1/db_1/inventory/Scripts/ext/lib/libclntsh.so.12.1
/u01/app/oracle/product/12.2.0.1/db_1/inventory/backup/2019-04-20_07-00-47PM/Scripts/ext/lib/libclntsh.so.12.1
/u01/app/oracle/product/12.2.0.1/db_1/lib/libclntsh.so
/u01/app/oracle/product/12.2.0.1/db_1/lib/libclntsh.so.10.1
/u01/app/oracle/product/12.2.0.1/db_1/lib/libclntsh.so.11.1
/u01/app/oracle/product/12.2.0.1/db_1/lib/libclntsh.so.12.1
/u01/database/stage/ext/lib/libclntsh.so.12.1
```
And when I go to playbook:

```
[oracle @ alderaan ansible] $ ansible-playbook oracle.yaml

PLAY [oracle] ********************************************** ************************************************** ************************************************** *****************************

TASK [Gathering Facts] ********************************************* ************************************************** ************************************************** *********************
ok: [192.168.1.150]

TASK [Run SQL] ********************************************* ************************************************** ************************************************** *****************************
fatal: [192.168.1.150]: FAILED! can not locate the 64-bit Oracle Client library: \ "libclntsh.so: can not open shared object file: no such file or directory \ ". See https: //********.github.io/odpi/doc/installation.html#linux for help, connect descriptor: (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP) (HOST = localhost) (PORT = 1521)) (CONNECT_DATA = (SERVICE_NAME = ORCL)))}
        to retry, use: --limit @ / etc / ansible / oracle.retry

PLAY RECAP ************************************************ ************************************************** ************************************************** ******************************
192.168.1.150: ok = 1 changed = 0 unreachable = 0 failed = 1
```

First the library error occurs, and another thing I noticed is that it is not replacing the host in the connection string.

User that I am running the playbook: oracle (the same owner of database installation)

If you can help me identify what I'm doing wrong, I'll be very grateful.

Thank you.

**Comment by oravirt** [comment]
```
- hosts: oracle
  user: oracle

  vars:
      oracle_home: /u01/app/oracle/product/12.2.0.1/db_1
      hostname: "192.168.1.150"
      service_name: ORCL
      set_init_mode: sysdba
      set_init_user: sys
      user: system
      password: oracle
      oracle_env:
             ORACLE_HOME: "{{oracle_home}}"
             LD_LIBRARY_PATH: "{{oracle_home}} / lib"   <--- Looks like extra spaces inside the quotes

  tasks
    - name: Run SQL
      oracle_sql:
        username: "{{user}}"
        password: "{{password}}"
        service_name: "{{service_name}}"
        sql: "select username from dba_users"
```
In the LD_LIBRARY_PATH variable, It looks like you have extra spaces in the string, they have to removed.

> another thing I noticed is that it is not replacing the host in the connection string.

You have to add the `hostname` variable to the oracle_sql task, i.e:
 ```
     oracle_sql:
        username: "{{user}}"
        password: "{{password}}"
        hostname: "{{ hostname }}"     < ------
        service_name: "{{service_name}}"
        sql: "select username from dba_users"
```
If you omit the `hostname` variable, it will default to localhost
