### ISSUE TITLE
oracle_pdb generates invalid SQL

### ISSUE THREAD

**Issue by willievu** [oravirt/ansible-oracle-modules#51]
It is caused by the "copy" clause.  After removing it like follows, it works.

#createsql += ' file_name_convert = (%s) copy' % (quoted)
  createsql += ' file_name_convert = (%s)' % (quoted)

The following is the error.

The full traceback is:
  File "/tmp/ansible_gSvzei/ansible_module_oracle_pdb.py", line 279, in execute_sql
    cursor.execute(sql)

fatal: [db]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datafile_dest": null,
            "file_name_convert": "/pdb1/, /cx_oracle_test_1/",
            "hostname": "<host ip>",
            "mode": "********dba",
            "name": "cx_oracle_test_1",
            "oracle_home": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pdb_admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pdb_admin_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": "1521",
            "save_state": true,
            "service_name": null,
            "service_name_convert": null,
            "sourcedb": "cdb12c",
            "state": "present",
            "unplug_dest": null,
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Something went wrong while executing sql - ORA-00922: missing or invalid option sql: create pluggable database cx_oracle_test_1  admin user ******** identified by ********  file_name_convert = ('/pdb1/',' /cx_oracle_test_1/') copy"
}

**Comment by oravirt** [comment]
Can you show me the playbook?

**Comment by willievu** [comment]
Yes I'm trying to create a new pdb.

Here is the playbook:

```
---  
- hosts: db
  vars:
    hostname: "{{ database_host }}"
    user: sys
    password: "{{ database_admin_password | b64decode }}"
    uim_pdb_name: "cx_oracle_test_1"
  tasks:
    - name: Create pluggable database
      oracle_pdb: 
        name: "{{ uim_pdb_name }}"
        sourcedb: "{{ uim_database_sid }}"
        mode: sysdba
        hostname: "{{ hostname }}"
        user: "{{ user }}"
        password: "{{ password }}"
        pdb_admin_password: sys
        pdb_admin_username: "{{ database_admin_password | b64decode }}"
        file_name_convert: "/pdbseed/,/{{ pdb_name }}/"
```
