### ISSUE TITLE
Unable to execute module from macOS

### ISSUE THREAD

**Issue by johnjelinek** [oravirt/ansible-oracle-modules#77]
From ansible, I see:
```
The cx_Oracle module is required. 'pip install cx_Oracle' should do the trick. If cx_Oracle is installed, make sure ORACLE_HOME & LD_LIBRARY_datafile is set
```

However, if I run a simple python script, it succeeds:
```
# myscript.py

from __future__ import print_function

import cx_Oracle

# Connect as user "hr" with password "welcome" to the "oraclepdb" service running on this computer.
connection = cx_Oracle.connect("hr", "welcome", "localhost/oraclepdb")

cursor = connection.cursor()
cursor.execute("""
    SELECT username
  FROM dba_users""")
for username in cursor:
    print("Values:", username)

print("done")
```
running with `/usr/local/Cellar/ansible/2.5.4/libexec/bin/python myscript.py` after installing the deps like this: `/usr/local/Cellar/ansible/2.5.4/libexec/bin/python -m pip install cx_Oracle --upgrade`.

Not sure why the module is failing.

**Comment by johnjelinek** [comment]
note: I've never heard of `LD_LIBRARY_datafile` before -- not sure what that should be set to. `ORACLE_HOME` and `LD_LIBRARY` are set though.

**Comment by oravirt** [comment]
Hi,
First of all, thanks for trying this out!

re: `LD_LIBRARY_datafile`, that's an extremely weird (ad unfortunate) typo. It should be `LD_LIBRARY_PATH` and nothing else ;-) 

Can you show me the playbook you're trying to run?

**Comment by johnjelinek** [comment]
```
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: create domain tablespace
    oracle_tablespace:
      hostname: "{{ RDS_HOST }}"
      service_name: "{{ RDS_SERVICE_NAME }}"
      user: "{{ RDS_USER }}"
      password: "{{ RDS_PASSWORD }}"
      tablespace: domain_data
      size: 5G
      autoextend: true
      next: 1G 
      max: 15G
```

This works fine on my linux box, not sure why it's not working on macOS. As mentioned above, I can query from oracle within ansible's embedded python version. I can also query from my pyenv environment.
